[package]
name = "nerve"
version = "1.0.0"
edition = "2021"

[dependencies]
winit = "0.30.8"
glfw = { version = "0.59.0", features = ["vulkan"] }
gll = { path = "../gll" }
flate2 = "1.0.35"

cgmath = "0.18.0"
lazy_static = "1.5.0"