[package]
name = "nerve"
version = "1.0.0"
edition = "2021"

[dependencies]
glfw = { version = "0.59.0", features = ["vulkan"] }
gll = { git = "https://github.com/Kono-o/gll.git", branch = "main" }

cgmath = "0.18.0"
png = "0.17.15"

lazy_static = "1.5.0"